### ISSUE TITLE
Improve website for mobile phones

### ISSUE THREAD

**Issue by vlcty** [vlcty/ipv6-overview.xyz#1]
I'm not a frontend developer. This is my first real try and I think it look great on my desktop two 2K monitors. I've tried it also on tablets with the firefox developer console. But on mobile phones it looks shitty. This should be changed.

**Comment by vlcty** [comment]
I've hidden the result table on smartphones. Maybe small tables are also affected.

**Comment by 4ndyZ** [comment]
With my last to merges (#22 and #23) this issue should be closed. The website is now fully responsive and loads blazing fast.
