### ISSUE TITLE
Add SBC manufacturers

### ISSUE THREAD

**Issue by vlcty** [vlcty/ipv6-overview.xyz#13]
Add the popular single board computers manufacturers:

- [x] Raspberry Pi
- [x] Pine64
- [x] Beagle Bone
- [ ] ~Orange Pi~ No TLS!
- [ ] ~Banana Pi~ No TLS!
- [ ] Odroid

**Comment by 4ndyZ** [comment]
I think this issue should be closed Odroid got added in #21
